export const SUPPORTED_LANGUAGES = [
  { code: 'mr', name: 'मराठी', english: 'Marathi', sarvam: 'mr-IN', speech: 'mr-IN' },
  { code: 'hi', name: 'हिंदी', english: 'Hindi', sarvam: 'hi-IN', speech: 'hi-IN' },
  { code: 'ta', name: 'தமிழ்', english: 'Tamil', sarvam: 'ta-IN', speech: 'ta-IN' },
  { code: 'te', name: 'తెలుగు', english: 'Telugu', sarvam: 'te-IN', speech: 'te-IN' },
  { code: 'kn', name: 'ಕನ್ನಡ', english: 'Kannada', sarvam: 'kn-IN', speech: 'kn-IN' },
  { code: 'ml', name: 'മലയാളം', english: 'Malayalam', sarvam: 'ml-IN', speech: 'ml-IN' },
  { code: 'gu', name: 'ગુજરાતી', english: 'Gujarati', sarvam: 'gu-IN', speech: 'gu-IN' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ', english: 'Punjabi', sarvam: 'pa-IN', speech: 'pa-IN' },
  { code: 'bn', name: 'বাংলা', english: 'Bengali', sarvam: 'bn-IN', speech: 'bn-IN' },
  { code: 'or', name: 'ଓଡ଼ିଆ', english: 'Odia', sarvam: 'or-IN', speech: 'or-IN' },
  { code: 'as', name: 'অসমীয়া', english: 'Assamese', sarvam: 'as-IN', speech: 'as-IN' },
  { code: 'ks', name: 'کٲشُر', english: 'Kashmiri', sarvam: 'ks-IN', speech: 'ur-IN' },
  { code: 'ur', name: 'اردو', english: 'Urdu', sarvam: 'ur-IN', speech: 'ur-IN' },
  { code: 'mai', name: 'मैथिली', english: 'Maithili', sarvam: 'mai-IN', speech: 'hi-IN' },
  { code: 'doi', name: 'डोगरी', english: 'Dogri', sarvam: 'doi-IN', speech: 'hi-IN' },
  { code: 'kok', name: 'कोंकणी', english: 'Konkani', sarvam: 'kok-IN', speech: 'mr-IN' },
  { code: 'mni', name: 'মৈতৈলোন্', english: 'Manipuri', sarvam: 'mni-IN', speech: 'bn-IN' },
  { code: 'ne', name: 'नेपाली', english: 'Nepali', sarvam: 'ne-IN', speech: 'ne-NP' },
  { code: 'sa', name: 'संस्कृत', english: 'Sanskrit', sarvam: 'sa-IN', speech: 'hi-IN' },
  { code: 'sat', name: 'ᱥᱟᱱᱛᱟᱲᱤ', english: 'Santali', sarvam: 'sat-IN', speech: 'hi-IN' },
];

export const UI_TRANSLATIONS = {
  mr: {
    greeting: 'नमस्कार', how_are_you: 'आज तुम्हाला कसं वाटतंय?',
    speak_with_vaidya: 'वैद्याशी बोला', your_complaint: 'तुमची तक्रार सांगा',
    quick_symptoms: 'त्वरित लक्षणे', emergency: 'आणीबाणी',
    disclaimer: '⚠️ वैद्या हा डॉक्टरचा पर्याय नाही',
    type_here: 'तुमची तक्रार इथे लिहा...', send: 'पाठवा',
    listen: '🔊 ऐका', correct_this: 'हे चुकीचे आहे',
    asha_workers: 'ASHA कार्यकर्ता', available_workers: 'जवळच्या उपलब्ध कार्यकर्त्या',
    call_108: '🚨 तातडीने 108 वर कॉल करा', talk_to_asha: '👩‍⚕️ ASHA ताईंशी बोला',
    history: 'मागील संवाद', profile: 'माझी माहिती', save: 'माहिती जतन करा',
    logout: 'लॉगआउट करा', corrections: 'सुधारणा', quality: 'गुणवत्ता', dialects: 'बोली',
    welcome_title: 'नमस्कार, मी वैद्या', welcome_sub: 'तुमची तक्रार मराठीत सांगा',
    asha_context_medium: 'तुम्हाला ASHA ताईंशी बोलणे उपयुक्त ठरेल.',
    asha_context_high: 'हे लक्षण गंभीर असू शकते. ASHA ताईंशी लगेच बोला.',
    emergency_context: 'ही आणीबाणी आहे. तातडीने 108 वर कॉल करा!'
  },
  hi: {
    greeting: 'नमस्ते', how_are_you: 'आज आप कैसा महसूस कर रहे हैं?',
    speak_with_vaidya: 'वैद्या से बात करें', your_complaint: 'अपनी तकलीफ बताएं',
    quick_symptoms: 'त्वरित लक्षण', emergency: 'आपातकाल',
    disclaimer: '⚠️ वैद्या डॉक्टर का विकल्प नहीं है',
    type_here: 'अपनी तकलीफ यहाँ लिखें...', send: 'भेजें',
    listen: '🔊 सुनें', correct_this: 'यह गलत है',
    asha_workers: 'ASHA कार्यकर्ता', available_workers: 'नजदीकी उपलब्ध कार्यकर्ता',
    call_108: '🚨 तुरंत 108 पर कॉल करें', talk_to_asha: '👩‍⚕️ ASHA दीदी से बात करें',
    history: 'पिछली बातचीत', profile: 'मेरी जानकारी', save: 'जानकारी सहेजें',
    logout: 'लॉगआउट करें', corrections: 'सुधार', quality: 'गुणवत्ता', dialects: 'बोली',
    welcome_title: 'नमस्ते, मैं वैद्या हूँ', welcome_sub: 'अपनी तकलीफ हिंदी में बताएं',
    asha_context_medium: 'आपको ASHA दीदी से बात करना फायदेमंद होगा।',
    asha_context_high: 'यह लक्षण गंभीर हो सकता है। ASHA दीदी से तुरंत बात करें।',
    emergency_context: 'यह आपातकाल है। तुरंत 108 पर कॉल करें!'
  },
  ta: {
    greeting: 'வணக்கம்', how_are_you: 'இன்று நீங்கள் எப்படி உணர்கிறீர்கள்?',
    speak_with_vaidya: 'வைத்யாவிடம் பேசுங்கள்', your_complaint: 'உங்கள் பிரச்சனையை சொல்லுங்கள்',
    quick_symptoms: 'விரைவு அறிகுறிகள்', emergency: 'அவசரநிலை',
    disclaimer: '⚠️ வைத்யா மருத்துவருக்கு மாற்றாக அல்ல',
    type_here: 'உங்கள் பிரச்சனையை இங்கே எழுதுங்கள்...', send: 'அனுப்பு',
    listen: '🔊 கேளுங்கள்', correct_this: 'இது தவறு',
    asha_workers: 'ASHA பணியாளர்', available_workers: 'அருகிலுள்ள கிடைக்கக்கூடிய பணியாளர்கள்',
    call_108: '🚨 உடனே 108 ஐ அழைக்கவும்', talk_to_asha: '👩‍⚕️ ASHA அக்காவிடம் பேசுங்கள்',
    history: 'கடந்த உரையாடல்கள்', profile: 'என் தகவல்', save: 'தகவலை சேமிக்கவும்',
    logout: 'வெளியேறு', corrections: 'திருத்தங்கள்', quality: 'தரம்', dialects: 'வட்டார மொழி',
    welcome_title: 'வணக்கம், நான் வைத்யா', welcome_sub: 'உங்கள் பிரச்சனையை தமிழில் சொல்லுங்கள்',
    asha_context_medium: 'ASHA அக்காவிடம் பேசுவது உதவியாக இருக்கும்.',
    asha_context_high: 'இந்த அறிகுறி தீவிரமாக இருக்கலாம். ASHA அக்காவிடம் உடனே பேசுங்கள்.',
    emergency_context: 'இது அவசரநிலை. உடனே 108 ஐ அழைக்கவும்!'
  },
  ml: {
    greeting: 'നമസ്കാരം', how_are_you: 'ഇന്ന് നിങ്ങൾക്ക് എങ്ങനെ തോന്നുന്നു?',
    speak_with_vaidya: 'വൈദ്യയോട് സംസാരിക്കൂ', your_complaint: 'നിങ്ങളുടെ പ്രശ്നം പറയൂ',
    quick_symptoms: 'ദ്രുത ലക്ഷണങ്ങൾ', emergency: 'അടിയന്തരാവസ്ഥ',
    disclaimer: '⚠️ വൈദ്യ ഡോക്ടറുടെ പകരക്കാരനല്ല',
    type_here: 'നിങ്ങളുടെ പ്രശ്നം ഇവിടെ എഴുതൂ...', send: 'അയക്കൂ',
    listen: '🔊 കേൾക്കൂ', correct_this: 'ഇത് തെറ്റാണ്',
    asha_workers: 'ASHA പ്രവർത്തകർ', available_workers: 'സമീപത്തുള്ള ലഭ്യമായ പ്രവർത്തകർ',
    call_108: '🚨 ഉടനടി 108 ൽ വിളിക്കൂ', talk_to_asha: '👩‍⚕️ ASHA ചേച്ചിയോട് സംസാരിക്കൂ',
    history: 'കഴിഞ്ഞ സംഭാഷണങ്ങൾ', profile: 'എന്റെ വിവരങ്ങൾ', save: 'വിവരങ്ങൾ സേവ് ചെയ്യൂ',
    logout: 'ലോഗ്ഔട്ട്', corrections: 'തിരുത്തലുകൾ', quality: 'ഗുണനിലവാരം', dialects: 'ഭാഷാഭേദം',
    welcome_title: 'നമസ്കാരം, ഞാൻ വൈദ്യ', welcome_sub: 'നിങ്ങളുടെ പ്രശ്നം മലയാളത്തിൽ പറയൂ',
    asha_context_medium: 'ASHA ചേച്ചിയോട് സംസാരിക്കുന്നത് ഉപകാരപ്രദമായിരിക്കും.',
    asha_context_high: 'ഈ ലക്ഷണം ഗുരുതരമായിരിക്കാം. ASHA ചേച്ചിയോട് ഉടനടി സംസാരിക്കൂ.',
    emergency_context: 'ഇത് അടിയന്തരാവസ്ഥയാണ്. ഉടനടി 108 ൽ വിളിക്കൂ!'
  },
  as: {
    greeting: 'নমস্কাৰ', how_are_you: 'আজি আপুনি কেনে অনুভৱ কৰিছে?',
    speak_with_vaidya: 'বৈদ্যাৰ সৈতে কথা পাতক', your_complaint: 'আপোনাৰ সমস্যা কওক',
    quick_symptoms: 'দ্ৰুত লক্ষণসমূহ', emergency: 'জৰুৰীকালীন অৱস্থা',
    disclaimer: '⚠️ বৈদ্যা চিকিৎসকৰ বিকল্প নহয়',
    type_here: 'আপোনাৰ সমস্যা ইয়াত লিখক...', send: 'পঠাওক',
    listen: '🔊 শুনক', correct_this: 'এইটো ভুল',
    asha_workers: 'ASHA কৰ্মী', available_workers: 'ওচৰৰ উপলব্ধ কৰ্মীসকল',
    call_108: '🚨 তৎক্ষণাৎ 108 ত ফোন কৰক', talk_to_asha: '👩‍⚕️ ASHA বাইদেউৰ সৈতে কথা পাতক',
    history: 'পূৰ্বৰ কথোপকথন', profile: 'মোৰ তথ্য', save: 'তথ্য সংৰক্ষণ কৰক',
    logout: 'লগআউট', corrections: 'সংশোধন', quality: 'গুণগতমান', dialects: 'উপভাষা',
    welcome_title: 'নমস্কাৰ, মই বৈদ্যা', welcome_sub: 'আপোনাৰ সমস্যা অসমীয়াত কওক',
    asha_context_medium: 'ASHA বাইদেউৰ সৈতে কথা পতাটো উপকাৰী হ\'ব।',
    asha_context_high: 'এই লক্ষণটো গুৰুতৰ হ\'ব পাৰে। ASHA বাইদেউৰ সৈতে তৎক্ষণাৎ কথা পাতক।',
    emergency_context: 'এইটো জৰুৰীকালীন অৱস্থা। তৎক্ষণাৎ 108 ত ফোন কৰক!'
  },
  ks: {
    greeting: 'آداب', how_are_you: 'آج تُہند حال کیا چھُ؟',
    speak_with_vaidya: 'وید٘یا سیتھ گل کرو', your_complaint: 'آپنہِ تکلیف دَسو',
    quick_symptoms: 'جلد علامات', emergency: 'ہنگامی صورتحال',
    disclaimer: '⚠️ وید٘یا ڈاکٹر کہ بدل نہٕ چھُ',
    type_here: 'آپنہِ تکلیف یتھۍ لیکھو...', send: 'پٹھاوو',
    listen: '🔊 اکھو', correct_this: 'یہ غلط چھُ',
    asha_workers: 'ASHA کارکُن', available_workers: 'نزدیکی دستیاب کارکنان',
    call_108: '🚨 فوری 108 ہند نمبر لگاوو', talk_to_asha: '👩‍⚕️ ASHA بہنہ سیتھ گل کرو',
    history: 'پرانہ گفتگو', profile: 'مہ معلومات', save: 'معلومات محفوظ کرو',
    logout: 'لاگ آوٗٹ', corrections: 'اصلاح', quality: 'معیار', dialects: 'بولی',
    welcome_title: 'آداب، بہٕ وید٘یا چھُس', welcome_sub: 'آپنہِ تکلیف کٲشُرِس مَنز دَسو',
    asha_context_medium: 'ASHA بہنہ سیتھ گل کرنۍ فائدہ مند ٲسِ۔',
    asha_context_high: 'یُہ علامت سنجیدہ ٲسِ سکٕنہٕ۔ ASHA بہنہ سیتھ ابی گل کرو۔',
    emergency_context: 'یُہ ہنگامی صورتحال چھیہٕ۔ ابی 108 ہند نمبر لگاوو!'
  },
  te: {
  greeting: 'నమస్కారం',
  how_are_you: 'ఈ రోజు మీకు ఎలా అనిపిస్తోంది?',
  speak_with_vaidya: 'వైద్యాతో మాట్లాడండి',
  your_complaint: 'మీ సమస్య చెప్పండి',
  quick_symptoms: 'త్వరిత లక్షణాలు',
  emergency: 'అత్యవసర పరిస్థితి',
  disclaimer: '⚠️ వైద్యా డాక్టర్‌కు ప్రత్యామ్నాయం కాదు',
  type_here: 'మీ సమస్యను ఇక్కడ రాయండి...',
  send: 'పంపండి',
  listen: '🔊 వినండి',
  correct_this: 'ఇది తప్పు',
  asha_workers: 'ASHA కార్యకర్త',
  available_workers: 'సమీపంలో అందుబాటులో ఉన్న కార్యకర్తలు',
  call_108: '🚨 వెంటనే 108 కు కాల్ చేయండి',
  talk_to_asha: '👩‍⚕️ ASHA అక్కతో మాట్లాడండి',
  history: 'గత సంభాషణలు',
  profile: 'నా సమాచారం',
  save: 'సమాచారం సేవ్ చేయండి',
  logout: 'లాగ్ అవుట్',
  corrections: 'సవరణలు',
  quality: 'నాణ్యత',
  dialects: 'మాండలికాలు',
  welcome_title: 'నమస్కారం, నేను వైద్యా',
  welcome_sub: 'మీ సమస్యను తెలుగులో చెప్పండి',
  asha_context_medium: 'ASHA అక్కతో మాట్లాడటం మీకు ఉపయోగకరంగా ఉంటుంది.',
  asha_context_high: 'ఈ లక్షణం తీవ్రమైనది కావచ్చు. వెంటనే ASHA అక్కతో మాట్లాడండి.',
  emergency_context: 'ఇది అత్యవసర పరిస్థితి. వెంటనే 108 కు కాల్ చేయండి!'
},

kn: {
  greeting: 'ನಮಸ್ಕಾರ',
  how_are_you: 'ಇಂದು ನಿಮಗೆ ಹೇಗಿದೆ?',
  speak_with_vaidya: 'ವೈದ್ಯರೊಂದಿಗೆ ಮಾತನಾಡಿ',
  your_complaint: 'ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ಹೇಳಿ',
  quick_symptoms: 'ತ್ವರಿತ ಲಕ್ಷಣಗಳು',
  emergency: 'ತುರ್ತು ಪರಿಸ್ಥಿತಿ',
  disclaimer: '⚠️ ವೈದ್ಯರು ಡಾಕ್ಟರ್‌ಗೆ ಪರ್ಯಾಯವಲ್ಲ',
  type_here: 'ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ಇಲ್ಲಿ ಬರೆಯಿರಿ...',
  send: 'ಕಳುಹಿಸಿ',
  listen: '🔊 ಕೇಳಿ',
  correct_this: 'ಇದು ತಪ್ಪಾಗಿದೆ',
  asha_workers: 'ASHA ಕಾರ್ಯಕರ್ತೆ',
  available_workers: 'ಹತ್ತಿರದ ಲಭ್ಯ ಕಾರ್ಯಕರ್ತರು',
  call_108: '🚨 ತಕ್ಷಣ 108 ಗೆ ಕರೆ ಮಾಡಿ',
  talk_to_asha: '👩‍⚕️ ASHA ಅಕ್ಕನೊಂದಿಗೆ ಮಾತನಾಡಿ',
  history: 'ಹಿಂದಿನ ಸಂಭಾಷಣೆಗಳು',
  profile: 'ನನ್ನ ಮಾಹಿತಿ',
  save: 'ಮಾಹಿತಿ ಉಳಿಸಿ',
  logout: 'ಲಾಗ್ ಔಟ್',
  corrections: 'ಸವರಣೆಗಳು',
  quality: 'ಗುಣಮಟ್ಟ',
  dialects: 'ಉಪಭಾಷೆಗಳು',
  welcome_title: 'ನಮಸ್ಕಾರ, ನಾನು ವೈದ್ಯ',
  welcome_sub: 'ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ಕನ್ನಡದಲ್ಲಿ ಹೇಳಿ',
  asha_context_medium: 'ASHA ಅಕ್ಕನೊಂದಿಗೆ ಮಾತನಾಡುವುದು ಉಪಯುಕ್ತವಾಗಬಹುದು.',
  asha_context_high: 'ಈ ಲಕ್ಷಣ ಗಂಭೀರವಾಗಿರಬಹುದು. ತಕ್ಷಣ ASHA ಅಕ್ಕನೊಂದಿಗೆ ಮಾತನಾಡಿ.',
  emergency_context: 'ಇದು ತುರ್ತು ಪರಿಸ್ಥಿತಿ. ತಕ್ಷಣ 108 ಗೆ ಕರೆ ಮಾಡಿ!'
},

gu: {
  greeting: 'નમસ્તે',
  how_are_you: 'આજે તમને કેમ લાગે છે?',
  speak_with_vaidya: 'વૈદ્ય સાથે વાત કરો',
  your_complaint: 'તમારી તકલીફ જણાવો',
  quick_symptoms: 'ઝડપી લક્ષણો',
  emergency: 'આપાતકાલીન સ્થિતિ',
  disclaimer: '⚠️ વૈદ્ય ડોક્ટરનો વિકલ્પ નથી',
  type_here: 'તમારી તકલીફ અહીં લખો...',
  send: 'મોકલો',
  listen: '🔊 સાંભળો',
  correct_this: 'આ ખોટું છે',
  asha_workers: 'ASHA કાર્યકર',
  available_workers: 'નજીકના ઉપલબ્ધ કાર્યકરો',
  call_108: '🚨 તરત જ 108 પર કોલ કરો',
  talk_to_asha: '👩‍⚕️ ASHA બહેન સાથે વાત કરો',
  history: 'પહેલાની વાતચીત',
  profile: 'મારી માહિતી',
  save: 'માહિતી સેવ કરો',
  logout: 'લોગઆઉટ કરો',
  corrections: 'સુધારાઓ',
  quality: 'ગુણવત્તા',
  dialects: 'બોલી',
  welcome_title: 'નમસ્તે, હું વૈદ્ય છું',
  welcome_sub: 'તમારી તકલીફ ગુજરાતીમાં જણાવો',
  asha_context_medium: 'તમારે ASHA બહેન સાથે વાત કરવી ઉપયોગી રહેશે.',
  asha_context_high: 'આ લક્ષણ ગંભીર હોઈ શકે છે. તરત જ ASHA બહેન સાથે વાત કરો.',
  emergency_context: 'આ આપાતકાલીન સ્થિતિ છે. તરત જ 108 પર કોલ કરો!'
},

pa: {
  greeting: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ',
  how_are_you: 'ਅੱਜ ਤੁਹਾਨੂੰ ਕਿਵੇਂ ਮਹਿਸੂਸ ਹੋ ਰਿਹਾ ਹੈ?',
  speak_with_vaidya: 'ਵੈਦਿਆ ਨਾਲ ਗੱਲ ਕਰੋ',
  your_complaint: 'ਆਪਣੀ ਤਕਲੀਫ ਦੱਸੋ',
  quick_symptoms: 'ਤੁਰੰਤ ਲੱਛਣ',
  emergency: 'ਐਮਰਜੈਂਸੀ',
  disclaimer: '⚠️ ਵੈਦਿਆ ਡਾਕਟਰ ਦਾ ਬਦਲ ਨਹੀਂ ਹੈ',
  type_here: 'ਆਪਣੀ ਤਕਲੀਫ ਇੱਥੇ ਲਿਖੋ...',
  send: 'ਭੇਜੋ',
  listen: '🔊 ਸੁਣੋ',
  correct_this: 'ਇਹ ਗਲਤ ਹੈ',
  asha_workers: 'ASHA ਵਰਕਰ',
  available_workers: 'ਨੇੜਲੇ ਉਪਲਬਧ ਵਰਕਰ',
  call_108: '🚨 ਤੁਰੰਤ 108 ਤੇ ਕਾਲ ਕਰੋ',
  talk_to_asha: '👩‍⚕️ ASHA ਭੈਣ ਨਾਲ ਗੱਲ ਕਰੋ',
  history: 'ਪਿਛਲੀਆਂ ਗੱਲਬਾਤਾਂ',
  profile: 'ਮੇਰੀ ਜਾਣਕਾਰੀ',
  save: 'ਜਾਣਕਾਰੀ ਸੇਵ ਕਰੋ',
  logout: 'ਲਾਗਆਉਟ ਕਰੋ',
  corrections: 'ਸੁਧਾਰ',
  quality: 'ਗੁਣਵੱਤਾ',
  dialects: 'ਬੋਲੀ',
  welcome_title: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ, ਮੈਂ ਵੈਦਿਆ ਹਾਂ',
  welcome_sub: 'ਆਪਣੀ ਤਕਲੀਫ ਪੰਜਾਬੀ ਵਿੱਚ ਦੱਸੋ',
  asha_context_medium: 'ASHA ਭੈਣ ਨਾਲ ਗੱਲ ਕਰਨਾ ਤੁਹਾਡੇ ਲਈ ਮਦਦਗਾਰ ਹੋਵੇਗਾ.',
  asha_context_high: 'ਇਹ ਲੱਛਣ ਗੰਭੀਰ ਹੋ ਸਕਦਾ ਹੈ। ਤੁਰੰਤ ASHA ਭੈਣ ਨਾਲ ਗੱਲ ਕਰੋ.',
  emergency_context: 'ਇਹ ਐਮਰਜੈਂਸੀ ਹੈ। ਤੁਰੰਤ 108 ਤੇ ਕਾਲ ਕਰੋ!'
},

bn: {
  greeting: 'নমস্কার',
  how_are_you: 'আজ আপনার কেমন লাগছে?',
  speak_with_vaidya: 'বৈদ্যের সাথে কথা বলুন',
  your_complaint: 'আপনার সমস্যা বলুন',
  quick_symptoms: 'দ্রুত লক্ষণ',
  emergency: 'জরুরি অবস্থা',
  disclaimer: '⚠️ বৈদ্য ডাক্তারদের বিকল্প নয়',
  type_here: 'আপনার সমস্যা এখানে লিখুন...',
  send: 'পাঠান',
  listen: '🔊 শুনুন',
  correct_this: 'এটি ভুল',
  asha_workers: 'ASHA কর্মী',
  available_workers: 'নিকটবর্তী উপলব্ধ কর্মীরা',
  call_108: '🚨 অবিলম্বে 108 নম্বরে কল করুন',
  talk_to_asha: '👩‍⚕️ ASHA দিদির সাথে কথা বলুন',
  history: 'আগের কথোপকথন',
  profile: 'আমার তথ্য',
  save: 'তথ্য সংরক্ষণ করুন',
  logout: 'লগআউট করুন',
  corrections: 'সংশোধন',
  quality: 'গুণমান',
  dialects: 'উপভাষা',
  welcome_title: 'নমস্কার, আমি বৈদ্য',
  welcome_sub: 'আপনার সমস্যা বাংলায় বলুন',
  asha_context_medium: 'ASHA দিদির সাথে কথা বলা আপনার জন্য সহায়ক হবে.',
  asha_context_high: 'এই লক্ষণটি গুরুতর হতে পারে। অবিলম্বে ASHA দিদির সাথে কথা বলুন.',
  emergency_context: 'এটি জরুরি অবস্থা। অবিলম্বে 108 নম্বরে কল করুন!'
},

or: {
  greeting: 'ନମସ୍କାର',
  how_are_you: 'ଆଜି ଆପଣଙ୍କୁ କେମିତି ଲାଗୁଛି?',
  speak_with_vaidya: 'ବୈଦ୍ୟଙ୍କ ସହ କଥାହୁଅନ୍ତୁ',
  your_complaint: 'ଆପଣଙ୍କ ସମସ୍ୟା କହନ୍ତୁ',
  quick_symptoms: 'ତୁରନ୍ତ ଲକ୍ଷଣ',
  emergency: 'ଜରୁରୀ ସ୍ଥିତି',
  disclaimer: '⚠️ ବୈଦ୍ୟ ଡାକ୍ତରଙ୍କ ପରିବର୍ତ୍ତେ ନୁହେଁ',
  type_here: 'ଆପଣଙ୍କ ସମସ୍ୟା ଏଠାରେ ଲେଖନ୍ତୁ...',
  send: 'ପଠାନ୍ତୁ',
  listen: '🔊 ଶୁଣନ୍ତୁ',
  correct_this: 'ଏହା ଭୁଲ',
  asha_workers: 'ASHA କର୍ମୀ',
  available_workers: 'ନିକଟସ୍ଥ ଉପଲବ୍ଧ କର୍ମୀ',
  call_108: '🚨 ତୁରନ୍ତ 108 କୁ କଲ୍ କରନ୍ତୁ',
  talk_to_asha: '👩‍⚕️ ASHA ଦିଦିଙ୍କ ସହ କଥାହୁଅନ୍ତୁ',
  history: 'ପୂର୍ବ କଥୋପକଥନ',
  profile: 'ମୋର ସୂଚନା',
  save: 'ସୂଚନା ସଂରକ୍ଷଣ କରନ୍ତୁ',
  logout: 'ଲଗଆଉଟ୍ କରନ୍ତୁ',
  corrections: 'ସୁଧାର',
  quality: 'ଗୁଣବତ୍ତା',
  dialects: 'ବୋଲି',
  welcome_title: 'ନମସ୍କାର, ମୁଁ ବୈଦ୍ୟ',
  welcome_sub: 'ଆପଣଙ୍କ ସମସ୍ୟା ଓଡ଼ିଆରେ କହନ୍ତୁ',
  asha_context_medium: 'ASHA ଦିଦିଙ୍କ ସହ କଥାହେବା ଉପକାରୀ ହେବ.',
  asha_context_high: 'ଏହି ଲକ୍ଷଣ ଗୁରୁତର ହୋଇପାରେ। ତୁରନ୍ତ ASHA ଦିଦିଙ୍କ ସହ କଥାହୁଅନ୍ତୁ.',
  emergency_context: 'ଏହା ଜରୁରୀ ସ୍ଥିତି। ତୁରନ୍ତ 108 କୁ କଲ୍ କରନ୍ତୁ!'
},

ur: {
  greeting: 'السلام علیکم',
  how_are_you: 'آج آپ کو کیسا محسوس ہو رہا ہے؟',
  speak_with_vaidya: 'ویدیا سے بات کریں',
  your_complaint: 'اپنی تکلیف بتائیں',
  quick_symptoms: 'فوری علامات',
  emergency: 'ہنگامی صورتحال',
  disclaimer: '⚠️ ویدیا ڈاکٹر کا متبادل نہیں ہے',
  type_here: 'اپنی تکلیف یہاں لکھیں...',
  send: 'بھیجیں',
  listen: '🔊 سنیں',
  correct_this: 'یہ غلط ہے',
  asha_workers: 'ASHA کارکن',
  available_workers: 'قریبی دستیاب کارکن',
  call_108: '🚨 فوراً 108 پر کال کریں',
  talk_to_asha: '👩‍⚕️ ASHA بہن سے بات کریں',
  history: 'پچھلی گفتگو',
  profile: 'میری معلومات',
  save: 'معلومات محفوظ کریں',
  logout: 'لاگ آؤٹ کریں',
  corrections: 'اصلاحات',
  quality: 'معیار',
  dialects: 'بولی',
  welcome_title: 'السلام علیکم، میں ویدیا ہوں',
  welcome_sub: 'اپنی تکلیف اردو میں بتائیں',
  asha_context_medium: 'ASHA بہن سے بات کرنا آپ کے لیے مددگار ہوگا.',
  asha_context_high: 'یہ علامت سنگین ہو سکتی ہے۔ فوراً ASHA بہن سے بات کریں.',
  emergency_context: 'یہ ہنگامی صورتحال ہے۔ فوراً 108 پر کال کریں!'
},
mai: {
  greeting: 'नमस्कार',
  how_are_you: 'आइ अहाँ केहन महसूस कऽ रहल छी?',
  speak_with_vaidya: 'वैद्य सँ बात करू',
  your_complaint: 'अपन समस्या बताउ',
  quick_symptoms: 'जल्दी लक्षण',
  emergency: 'आपातकाल',
  disclaimer: '⚠️ वैद्य डॉक्टरक विकल्प नहि अछि',
  type_here: 'अपन समस्या एतय लिखू...',
  send: 'पठाउ',
  listen: '🔊 सुनू',
  correct_this: 'ई गलत अछि',
  asha_workers: 'ASHA कार्यकर्ता',
  available_workers: 'नजदीक उपलब्ध कार्यकर्ता',
  call_108: '🚨 तुरंत 108 पर कॉल करू',
  talk_to_asha: '👩‍⚕️ ASHA दीदी सँ बात करू',
  history: 'पिछला बातचीत',
  profile: 'हमर जानकारी',
  save: 'जानकारी सहेजू',
  logout: 'लॉगआउट करू',
  corrections: 'सुधार',
  quality: 'गुणवत्ता',
  dialects: 'बोली',
  welcome_title: 'नमस्कार, हम वैद्य छी',
  welcome_sub: 'अपन समस्या मैथिली मे बताउ',
  asha_context_medium: 'ASHA दीदी सँ बात करब अहाँ लेल उपयोगी होयत.',
  asha_context_high: 'ई लक्षण गंभीर भऽ सकैत अछि। तुरंत ASHA दीदी सँ बात करू.',
  emergency_context: 'ई आपातकाल अछि। तुरंत 108 पर कॉल करू!'
},

ne: {
  greeting: 'नमस्ते',
  how_are_you: 'आज तपाईंलाई कस्तो महसुस भइरहेको छ?',
  speak_with_vaidya: 'वैद्यसँग कुरा गर्नुहोस्',
  your_complaint: 'आफ्नो समस्या बताउनुहोस्',
  quick_symptoms: 'छिटो लक्षणहरू',
  emergency: 'आपतकाल',
  disclaimer: '⚠️ वैद्य डाक्टरको विकल्प होइन',
  type_here: 'आफ्नो समस्या यहाँ लेख्नुहोस्...',
  send: 'पठाउनुहोस्',
  listen: '🔊 सुन्नुहोस्',
  correct_this: 'यो गलत छ',
  asha_workers: 'ASHA कार्यकर्ता',
  available_workers: 'नजिकका उपलब्ध कार्यकर्ताहरू',
  call_108: '🚨 तुरुन्त 108 मा कल गर्नुहोस्',
  talk_to_asha: '👩‍⚕️ ASHA दिदीसँग कुरा गर्नुहोस्',
  history: 'अघिल्लो कुराकानी',
  profile: 'मेरो जानकारी',
  save: 'जानकारी सुरक्षित गर्नुहोस्',
  logout: 'लगआउट गर्नुहोस्',
  corrections: 'सुधारहरू',
  quality: 'गुणस्तर',
  dialects: 'बोली',
  welcome_title: 'नमस्ते, म वैद्य हुँ',
  welcome_sub: 'आफ्नो समस्या नेपालीमा बताउनुहोस्',
  asha_context_medium: 'ASHA दिदीसँग कुरा गर्नु तपाईंका लागि उपयोगी हुन सक्छ.',
  asha_context_high: 'यो लक्षण गम्भीर हुन सक्छ। तुरुन्त ASHA दिदीसँग कुरा गर्नुहोस्.',
  emergency_context: 'यो आपतकालीन अवस्था हो। तुरुन्त 108 मा कल गर्नुहोस्!'
},

mni: {
  greeting: 'ꯈꯨꯔꯨꯝꯖꯔꯤ',
  how_are_you: 'ꯉꯁꯤ ꯅꯍꯥꯛ ꯀꯔꯝꯅꯥ ꯐꯥꯎꯔꯤ?',
  speak_with_vaidya: 'ꯚꯩꯗ꯭ꯌꯒꯥ ꯋꯥ ꯉꯥꯡꯉꯨ',
  your_complaint: 'ꯅꯍꯥꯛꯀꯤ ꯑꯔꯥꯝꯕ ꯍꯥꯌꯨ',
  quick_symptoms: 'ꯊꯨꯅꯥ ꯎꯕ ꯂꯛꯁꯟ',
  emergency: 'ꯃꯔꯨꯑꯣꯏꯕ ꯑꯋꯥꯕ',
  disclaimer: '⚠️ ꯚꯩꯗ꯭ꯌ ꯗꯣꯛꯇꯔꯒꯤ ꯃꯍꯨꯠ ꯅꯠꯇꯦ',
  type_here: 'ꯅꯍꯥꯛꯀꯤ ꯑꯔꯥꯝꯕ ꯃꯐꯝꯁꯤꯗ ꯏꯕꯤꯌꯨ...',
  send: 'ꯊꯥꯕꯤꯌꯨ',
  listen: '🔊 ꯇꯥꯕꯤꯌꯨ',
  correct_this: 'ꯃꯁꯤ ꯂꯥꯜꯂꯤ',
  asha_workers: 'ASHA ꯋꯥꯔꯀꯔ',
  available_workers: 'ꯅꯥꯛꯅꯕ ꯐꯪꯂꯤꯕ ꯋꯥꯔꯀꯔꯁꯤꯡ',
  call_108: '🚨 ꯊꯨꯅꯥ 108 ꯗ ꯀꯣꯜ ꯇꯧꯕꯤꯌꯨ',
  talk_to_asha: '👩‍⚕️ ASHA ꯗꯤꯗꯤꯒꯥ ꯋꯥ ꯉꯥꯡꯉꯨ',
  history: 'ꯃꯃꯥꯡꯒꯤ ꯋꯥꯔꯤ',
  profile: 'ꯑꯩꯒꯤ ꯃꯔꯝ',
  save: 'ꯃꯔꯝ ꯁꯦꯚ ꯇꯧꯕꯤꯌꯨ',
  logout: 'ꯂꯣꯒꯑꯥꯎꯠ',
  corrections: 'ꯁꯦꯝꯒꯠꯄ',
  quality: 'ꯀ꯭ꯋꯥꯂꯤꯇꯤ',
  dialects: 'ꯂꯣꯜꯒꯤ ꯃꯑꯣꯡ',
  welcome_title: 'ꯈꯨꯔꯨꯝꯖꯔꯤ, ꯑꯩ ꯚꯩꯗ꯭ꯌ ꯑꯣꯏ',
  welcome_sub: 'ꯅꯍꯥꯛꯀꯤ ꯑꯔꯥꯝꯕ ꯃꯅꯤꯄꯨꯔꯤꯗ ꯍꯥꯌꯨ',
  asha_context_medium: 'ASHA ꯗꯤꯗꯤꯒꯥ ꯋꯥ ꯉꯥꯡꯕ ꯅꯍꯥꯛꯀꯤꯗꯃꯛ ꯀꯥꯅꯒꯅꯤ.',
  asha_context_high: 'ꯃꯁꯤ ꯃꯔꯨꯑꯣꯏꯕ ꯂꯛꯁꯟ ꯑꯣꯏꯕ ꯌꯥꯏ। ꯊꯨꯅꯥ ASHA ꯗꯤꯗꯤꯒꯥ ꯋꯥ ꯉꯥꯡꯉꯨ.',
  emergency_context: 'ꯃꯁꯤ ꯃꯔꯨꯑꯣꯏꯕ ꯑꯋꯥꯕꯅꯤ। ꯊꯨꯅꯥ 108 ꯗ ꯀꯣꯜ ꯇꯧꯕꯤꯌꯨ!'
},

sat: {
  greeting: 'ᱡᱚᱦᱟᱨ',
  how_are_you: 'ᱛᱮᱦᱮᱧ ᱟᱢ ᱪᱮᱫ ᱞᱮᱠᱟ ᱵᱩᱡᱷᱟᱣᱟ?',
  speak_with_vaidya: 'ᱵᱟᱭᱫᱭᱟ ᱥᱟᱶ ᱨᱚᱲ ᱢᱮ',
  your_complaint: 'ᱟᱢᱟᱜ ᱫᱩᱠ ᱞᱟᱹᱭ ᱢᱮ',
  quick_symptoms: 'ᱞᱚᱜᱚᱱ ᱪᱤᱱᱦᱟᱹ',
  emergency: 'ᱟᱹᱭᱫᱟᱹᱨ',
  disclaimer: '⚠️ ᱵᱟᱭᱫᱭᱟ ᱫᱚ ᱰᱚᱠᱴᱚᱨ ᱨᱮᱱ ᱵᱚᱫᱚᱞ ᱵᱟᱝ ᱠᱟᱱᱟ',
  type_here: 'ᱟᱢᱟᱜ ᱫᱩᱠ ᱱᱚᱰᱮ ᱚᱞ ᱢᱮ...',
  send: 'ᱠᱩᱞ ᱢᱮ',
  listen: '🔊 ᱟᱧᱡᱚᱢ ᱢᱮ',
  correct_this: 'ᱱᱚᱶᱟ ᱵᱷᱩᱞ ᱜᱮᱭᱟ',
  asha_workers: 'ASHA ᱠᱟᱹᱢᱤᱭᱟᱹ',
  available_workers: 'ᱱᱟᱠᱷᱟ ᱨᱮ ᱢᱮᱱᱟᱜ ASHA ᱠᱟᱹᱢᱤᱭᱟᱹ',
  call_108: '🚨 ᱞᱚᱜᱚᱱ 108 ᱨᱮ ᱠᱚᱞ ᱢᱮ',
  talk_to_asha: '👩‍⚕️ ASHA ᱫᱤᱫᱤ ᱥᱟᱶ ᱨᱚᱲ ᱢᱮ',
  history: 'ᱢᱟᱲᱟᱝ ᱨᱚᱲ',
  profile: 'ᱤᱧᱟᱜ ᱵᱤᱵᱨᱚᱬ',
  save: 'ᱵᱤᱵᱨᱚᱬ ᱥᱟᱧᱪᱟᱣ ᱢᱮ',
  logout: 'ᱞᱚᱜᱟᱣᱩᱴ',
  corrections: 'ᱥᱩᱫᱷᱟᱨ',
  quality: 'ᱜᱩᱱ',
  dialects: 'ᱵᱚᱞᱤ',
  welcome_title: 'ᱡᱚᱦᱟᱨ, ᱤᱧ ᱵᱟᱭᱫᱭᱟ',
  welcome_sub: 'ᱟᱢᱟᱜ ᱫᱩᱠ ᱥᱟᱱᱛᱟᱲᱤ ᱨᱮ ᱞᱟᱹᱭ ᱢᱮ',
  asha_context_medium: 'ASHA ᱫᱤᱫᱤ ᱥᱟᱶ ᱨᱚᱲ ᱟᱢᱟᱜ ᱞᱟᱹᱜᱤᱫ ᱵᱮᱱᱟᱣ ᱦᱩᱭ ᱫᱟᱲᱮᱭᱟ.',
  asha_context_high: 'ᱱᱚᱶᱟ ᱪᱤᱱᱦᱟᱹ ᱜᱚᱢᱵᱷᱤᱨ ᱦᱩᱭ ᱫᱟᱲᱮᱭᱟ। ᱞᱚᱜᱚᱱ ASHA ᱫᱤᱫᱤ ᱥᱟᱶ ᱨᱚᱲ ᱢᱮ.',
  emergency_context: 'ᱱᱚᱶᱟ ᱟᱹᱭᱫᱟᱹᱨ ᱜᱮᱭᱟ। ᱞᱚᱜᱚᱱ 108 ᱨᱮ ᱠᱚᱞ ᱢᱮ!'
},
};

export function getUI(langCode) {
  return UI_TRANSLATIONS[langCode] || UI_TRANSLATIONS['mr'];
}

export function getLangName(langCode) {
  const lang = SUPPORTED_LANGUAGES.find(l => l.code === langCode);
  return lang ? lang.name : 'मराठी';
}

export function getSarvamCode(langCode) {
  const lang = SUPPORTED_LANGUAGES.find(l => l.code === langCode);
  return lang ? lang.sarvam : 'mr-IN';
}

export function getSpeechCode(langCode) {
  const lang = SUPPORTED_LANGUAGES.find(l => l.code === langCode);
  return lang ? lang.speech : 'mr-IN';
}